SLStudio.Utils.RemoveHighlighting(get_param('untitled', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_untitled', 'handle'));
annotate_port('gm_untitled/HDL_DUT', 0, 1, '');
annotate_port('gm_untitled/HDL_DUT/Discrete PID Controller', 1, 1, '');
annotate_port('gm_untitled/HDL_DUT/Discrete PID Controller', 1, 1, '');
annotate_port('untitled/HDL_DUT/Discrete PID Controller', 1, 1, '');
annotate_port('gm_untitled/HDL_DUT/Discrete-Time Integrator_reg', 0, 1, '');
annotate_port('gm_untitled/HDL_DUT/Discrete-Time Integrator_x_reg_wire', 0, 1, '');
annotate_port('gm_untitled/HDL_DUT/Gain', 0, 1, '');
annotate_port('gm_untitled/HDL_DUT/Subtract', 0, 1, '');
annotate_port('gm_untitled/HDL_DUT/Sum', 0, 1, '');
annotate_port('gm_untitled/HDL_DUT/Discrete PID Controller/Sum', 1, 1, '');
annotate_port('untitled/HDL_DUT/Discrete PID Controller/Sum/Sum_PID/Sum', 1, 1, '');
