-- -------------------------------------------------------------
-- 
-- File Name: O:\your_desired_folder\Ali\zz\hdl_prj\hdlsrc\untitled\HDL_DUT.vhd
-- Created: 2026-05-16 18:02:14
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HDL_DUT
-- Source Path: untitled/HDL_DUT
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY HDL_DUT IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        in1                               :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        in2                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En10
        out_rsvd                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En10
        );
END HDL_DUT;


ARCHITECTURE rtl OF HDL_DUT IS

  -- Component Declarations
  COMPONENT Discrete_PID_Controller
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          u                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En10
          y                               :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En10
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Discrete_PID_Controller
    USE ENTITY work.Discrete_PID_Controller(rtl);

  -- Signals
  SIGNAL in2_signed                       : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL s_state_out1                     : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL denom_gain1_mul_temp             : signed(63 DOWNTO 0);  -- sfix64_En20
  SIGNAL s_denom_gain1                    : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Discrete_Time_Integrator_x_reg   : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Unit_Delay_out1                  : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL s_nume_gain1                     : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Gain1_mul_temp                   : signed(63 DOWNTO 0);  -- sfix64_En37
  SIGNAL Gain1_out1                       : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Discrete_Time_Integrator_indtc   : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL gain_mul_temp                    : signed(63 DOWNTO 0);  -- sfix64_En37
  SIGNAL Discrete_Time_Integrator_u_gain  : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL Discrete_Time_Integrator_u_dtc   : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Discrete_Time_Integrator_u_add   : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Subtract_out1                    : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Gain_mul_temp_1                  : signed(63 DOWNTO 0);  -- sfix64_En37
  SIGNAL Gain_out1                        : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Sum_out1                         : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Discrete_PID_Controller_out1     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Discrete_PID_Controller_out1_signed : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Saturation_out1                  : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL s_denom_acc_out1                 : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL nume_gain1_mul_temp              : signed(63 DOWNTO 0);  -- sfix64_En20

BEGIN
  u_Discrete_PID_Controller : Discrete_PID_Controller
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              u => std_logic_vector(Sum_out1),  -- sfix32_En10
              y => Discrete_PID_Controller_out1  -- sfix32_En10
              );

  in2_signed <= signed(in2);

  denom_gain1_mul_temp <= to_signed(-974, 32) * s_state_out1;
  s_denom_gain1 <= denom_gain1_mul_temp(41 DOWNTO 10);

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= Discrete_Time_Integrator_x_reg;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  Gain1_mul_temp <= to_signed(1342177280, 32) * s_nume_gain1;
  Gain1_out1 <= Gain1_mul_temp(58 DOWNTO 27);

  Discrete_Time_Integrator_indtc <= Gain1_out1;

  gain_mul_temp <= to_signed(1374389535, 32) * Discrete_Time_Integrator_indtc;
  Discrete_Time_Integrator_u_gain <= resize(gain_mul_temp(63 DOWNTO 37), 32);

  Discrete_Time_Integrator_u_dtc <= Discrete_Time_Integrator_u_gain;

  Discrete_Time_Integrator_u_add <= Discrete_Time_Integrator_x_reg + Discrete_Time_Integrator_u_dtc;

  Discrete_Time_Integrator_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Discrete_Time_Integrator_x_reg <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Discrete_Time_Integrator_x_reg <= Discrete_Time_Integrator_u_add;
      END IF;
    END IF;
  END PROCESS Discrete_Time_Integrator_reg_process;


  Subtract_out1 <= Discrete_Time_Integrator_x_reg - Unit_Delay_out1;

  Gain_mul_temp_1 <= to_signed(1342177280, 32) * Subtract_out1;
  Gain_out1 <= Gain_mul_temp_1(58 DOWNTO 27);

  Sum_out1 <= in2_signed - Gain_out1;

  Discrete_PID_Controller_out1_signed <= signed(Discrete_PID_Controller_out1);

  
  Saturation_out1 <= to_signed(102400, 32) WHEN Discrete_PID_Controller_out1_signed > to_signed(102400, 32) ELSE
      to_signed(0, 32) WHEN Discrete_PID_Controller_out1_signed < to_signed(0, 32) ELSE
      Discrete_PID_Controller_out1_signed;

  s_denom_acc_out1 <= Saturation_out1 - s_denom_gain1;

  s_state_out1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      s_state_out1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        s_state_out1 <= s_denom_acc_out1;
      END IF;
    END IF;
  END PROCESS s_state_out1_1_process;


  nume_gain1_mul_temp <= to_signed(2497, 32) * s_state_out1;
  s_nume_gain1 <= nume_gain1_mul_temp(41 DOWNTO 10);

  out_rsvd <= std_logic_vector(s_nume_gain1);

END rtl;

