-- -------------------------------------------------------------
-- 
-- File Name: O:\your_desired_folder\Ali\zz\hdl_prj\hdlsrc\untitled\untitled.vhd
-- Created: 2026-05-16 18:02:14
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.01
-- Target subsystem base rate: 0.01
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: untitled
-- Source Path: untitled
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY untitled IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic
        );
END untitled;


ARCHITECTURE rtl OF untitled IS

  -- Component Declarations
  COMPONENT HDL_DUT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          in1                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          in2                             :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En10
          out_rsvd                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En10
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : HDL_DUT
    USE ENTITY work.HDL_DUT(rtl);

  -- Signals
  SIGNAL Constant_out1                    : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Constant1_out1                   : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL HDL_DUT_out1                     : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  -- Note: This model is configured with 'hdlsetup'
  -- 
  -- Add your design targeted for ASIC/FPGA inside HDL_DUT and then run the following command:
  -- makehdl('HDL_DUT')
  -- 
  -- Copyright 2015-2016 The MathWorks, Inc.

  u_HDL_DUT : HDL_DUT
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              in1 => std_logic_vector(Constant_out1),  -- ufix4
              in2 => std_logic_vector(Constant1_out1),  -- sfix32_En10
              out_rsvd => HDL_DUT_out1  -- sfix32_En10
              );


  Constant_out1 <= to_unsigned(16#0#, 4);

  Constant1_out1 <= to_signed(5120, 32);

END rtl;

