webtalk_init -webtalk_dir O:\\your_desired_folder\\Ali\\zz\\microblaze_led_7seg_uart_pwm\\microblaze_led_7seg_uart_pwm.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2026-06-17 21:34:50" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "kv8oplqpk5s2e27m5d1k6n3l9m" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.329 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1781711268328" -context "sdk\\\\hardware/1781711268328"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1781711268328"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1781711268328"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1781711268328"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1781711268328"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1781711268328"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1781711268328"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1781711268328"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1781711268328"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1781711268328"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1781711268328"
webtalk_add_data -client sdk -key uid -value "1781711410261" -context "sdk\\\\bsp/1781711410261"
webtalk_add_data -client sdk -key hwid -value "1781711268328" -context "sdk\\\\bsp/1781711410261"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1781711410261"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1781711410261"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1781711410261"
webtalk_add_data -client sdk -key uid -value "1781711426392" -context "sdk\\\\application/1781711426392"
webtalk_add_data -client sdk -key hwid -value "1781711268328" -context "sdk\\\\application/1781711426392"
webtalk_add_data -client sdk -key bspid -value "1781711410261" -context "sdk\\\\application/1781711426392"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1781711426392"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1781711426392"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1781711426392"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1781711426392"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1781711426392"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1781711426392"
webtalk_add_data -client sdk -key projSize -value "83.34765625" -context "sdk\\\\application/1781711426392"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1781715888984"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1781715888984"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1781715888984"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1781715888984"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1781715888984"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1781715888984"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1781715888984"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1781715888984"
webtalk_transmit -clientid 4178387941 -regid "" -xml O:\\your_desired_folder\\Ali\\zz\\microblaze_led_7seg_uart_pwm\\microblaze_led_7seg_uart_pwm.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html O:\\your_desired_folder\\Ali\\zz\\microblaze_led_7seg_uart_pwm\\microblaze_led_7seg_uart_pwm.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm O:\\your_desired_folder\\Ali\\zz\\microblaze_led_7seg_uart_pwm\\microblaze_led_7seg_uart_pwm.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
