open_system('gm_SECTION10_2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SECTION10_2/HDL_DUT', 'user2');
annotate_port('gm_SECTION10_2/HDL_DUT', 0, 1, 'cp : 30.854 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SECTION10_2/HDL_DUT/Discrete PID Controller', 'user2');
annotate_port('gm_SECTION10_2/HDL_DUT/Discrete PID Controller', 1, 1, 'cp : 30.854 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SECTION10_2/HDL_DUT/Discrete-Time Integrator_reg', 'user1');
annotate_port('gm_SECTION10_2/HDL_DUT/Discrete-Time Integrator_reg', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SECTION10_2/HDL_DUT/Discrete-Time Integrator_x_reg_wire', 'user2');
annotate_port('gm_SECTION10_2/HDL_DUT/Discrete-Time Integrator_x_reg_wire', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SECTION10_2/HDL_DUT/Gain', 'user2');
annotate_port('gm_SECTION10_2/HDL_DUT/Gain', 0, 1, 'cp : 8.293 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SECTION10_2/HDL_DUT/Subtract', 'user2');
annotate_port('gm_SECTION10_2/HDL_DUT/Subtract', 0, 1, 'cp : 1.708 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_SECTION10_2/HDL_DUT/Sum', 'user2');
annotate_port('gm_SECTION10_2/HDL_DUT/Sum', 0, 1, 'cp : 8.293 ns');
