-- -------------------------------------------------------------
-- 
-- File Name: SECTION10_2\hdlsrc\SECTION10_2\Discrete_PID_Controller.vhd
-- Created: 2026-05-16 23:11:03
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Discrete_PID_Controller
-- Source Path: SECTION10_2/HDL_DUT/Discrete PID Controller
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Discrete_PID_Controller IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En10
        y                                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En10
        );
END Discrete_PID_Controller;


ARCHITECTURE rtl OF Discrete_PID_Controller IS

  -- Signals
  SIGNAL u_signed                         : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Proportional_Gain_mul_temp       : signed(63 DOWNTO 0);  -- sfix64_En20
  SIGNAL Parallel_P_Gain_out1             : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Integral_Gain_mul_temp           : signed(63 DOWNTO 0);  -- sfix64_En20
  SIGNAL I_Gain_out1                      : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Integrator_indtc                 : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL gain_mul_temp                    : signed(63 DOWNTO 0);  -- sfix64_En37
  SIGNAL Integrator_u_gain                : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL Integrator_u_dtc                 : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Integrator_x_reg                 : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Integrator_u_add                 : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL D_Gain_out1                      : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL N_Gain_out1                      : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Filter_indtc                     : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL gain_mul_temp_1                  : signed(63 DOWNTO 0);  -- sfix64_En37
  SIGNAL Filter_u_gain                    : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL Filter_u_dtc                     : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Filter_x_reg                     : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Filter_u_add                     : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Filter_out1                      : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Filter_Coefficient_mul_temp      : signed(63 DOWNTO 0);  -- sfix64_En20
  SIGNAL Sum_add_temp                     : signed(31 DOWNTO 0);  -- sfix32_En10
  SIGNAL Sum_out1                         : signed(31 DOWNTO 0);  -- sfix32_En10

BEGIN
  -- Feedback Features
  -- 
  -- Derivative
  -- 
  -- Integrator

  u_signed <= signed(u);

  Proportional_Gain_mul_temp <= to_signed(102, 32) * u_signed;
  Parallel_P_Gain_out1 <= Proportional_Gain_mul_temp(41 DOWNTO 10) + ('0' & (Proportional_Gain_mul_temp(9) AND (( NOT Proportional_Gain_mul_temp(63)) OR (Proportional_Gain_mul_temp(8) OR Proportional_Gain_mul_temp(7) OR Proportional_Gain_mul_temp(6) OR Proportional_Gain_mul_temp(5) OR Proportional_Gain_mul_temp(4) OR Proportional_Gain_mul_temp(3) OR Proportional_Gain_mul_temp(2) OR Proportional_Gain_mul_temp(1) OR Proportional_Gain_mul_temp(0)))));

  Integral_Gain_mul_temp <= to_signed(658, 32) * u_signed;
  I_Gain_out1 <= Integral_Gain_mul_temp(41 DOWNTO 10) + ('0' & (Integral_Gain_mul_temp(9) AND (( NOT Integral_Gain_mul_temp(63)) OR (Integral_Gain_mul_temp(8) OR Integral_Gain_mul_temp(7) OR Integral_Gain_mul_temp(6) OR Integral_Gain_mul_temp(5) OR Integral_Gain_mul_temp(4) OR Integral_Gain_mul_temp(3) OR Integral_Gain_mul_temp(2) OR Integral_Gain_mul_temp(1) OR Integral_Gain_mul_temp(0)))));

  Integrator_indtc <= I_Gain_out1;

  gain_mul_temp <= to_signed(1374389535, 32) * Integrator_indtc;
  Integrator_u_gain <= (resize(gain_mul_temp(63 DOWNTO 37), 32)) + ('0' & (gain_mul_temp(36) AND (( NOT gain_mul_temp(63)) OR (gain_mul_temp(35) OR gain_mul_temp(34) OR gain_mul_temp(33) OR gain_mul_temp(32) OR gain_mul_temp(31) OR gain_mul_temp(30) OR gain_mul_temp(29) OR gain_mul_temp(28) OR gain_mul_temp(27) OR gain_mul_temp(26) OR gain_mul_temp(25) OR gain_mul_temp(24) OR gain_mul_temp(23) OR gain_mul_temp(22) OR gain_mul_temp(21) OR gain_mul_temp(20) OR gain_mul_temp(19) OR gain_mul_temp(18) OR gain_mul_temp(17) OR gain_mul_temp(16) OR gain_mul_temp(15) OR gain_mul_temp(14) OR gain_mul_temp(13) OR gain_mul_temp(12) OR gain_mul_temp(11) OR gain_mul_temp(10) OR gain_mul_temp(9) OR gain_mul_temp(8) OR gain_mul_temp(7) OR gain_mul_temp(6) OR gain_mul_temp(5) OR gain_mul_temp(4) OR gain_mul_temp(3) OR gain_mul_temp(2) OR gain_mul_temp(1) OR gain_mul_temp(0)))));

  Integrator_u_dtc <= Integrator_u_gain;

  Integrator_u_add <= Integrator_x_reg + Integrator_u_dtc;

  Integrator_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Integrator_x_reg <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Integrator_x_reg <= Integrator_u_add;
      END IF;
    END IF;
  END PROCESS Integrator_reg_process;


  D_Gain_out1 <= to_signed(0, 32);

  Filter_indtc <= N_Gain_out1;

  gain_mul_temp_1 <= to_signed(1374389535, 32) * Filter_indtc;
  Filter_u_gain <= (resize(gain_mul_temp_1(63 DOWNTO 37), 32)) + ('0' & (gain_mul_temp_1(36) AND (( NOT gain_mul_temp_1(63)) OR (gain_mul_temp_1(35) OR gain_mul_temp_1(34) OR gain_mul_temp_1(33) OR gain_mul_temp_1(32) OR gain_mul_temp_1(31) OR gain_mul_temp_1(30) OR gain_mul_temp_1(29) OR gain_mul_temp_1(28) OR gain_mul_temp_1(27) OR gain_mul_temp_1(26) OR gain_mul_temp_1(25) OR gain_mul_temp_1(24) OR gain_mul_temp_1(23) OR gain_mul_temp_1(22) OR gain_mul_temp_1(21) OR gain_mul_temp_1(20) OR gain_mul_temp_1(19) OR gain_mul_temp_1(18) OR gain_mul_temp_1(17) OR gain_mul_temp_1(16) OR gain_mul_temp_1(15) OR gain_mul_temp_1(14) OR gain_mul_temp_1(13) OR gain_mul_temp_1(12) OR gain_mul_temp_1(11) OR gain_mul_temp_1(10) OR gain_mul_temp_1(9) OR gain_mul_temp_1(8) OR gain_mul_temp_1(7) OR gain_mul_temp_1(6) OR gain_mul_temp_1(5) OR gain_mul_temp_1(4) OR gain_mul_temp_1(3) OR gain_mul_temp_1(2) OR gain_mul_temp_1(1) OR gain_mul_temp_1(0)))));

  Filter_u_dtc <= Filter_u_gain;

  Filter_u_add <= Filter_x_reg + Filter_u_dtc;

  Filter_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Filter_x_reg <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Filter_x_reg <= Filter_u_add;
      END IF;
    END IF;
  END PROCESS Filter_reg_process;


  Filter_out1 <= D_Gain_out1 - Filter_x_reg;

  Filter_Coefficient_mul_temp <= to_signed(21238, 32) * Filter_out1;
  N_Gain_out1 <= Filter_Coefficient_mul_temp(41 DOWNTO 10) + ('0' & (Filter_Coefficient_mul_temp(9) AND (( NOT Filter_Coefficient_mul_temp(63)) OR (Filter_Coefficient_mul_temp(8) OR Filter_Coefficient_mul_temp(7) OR Filter_Coefficient_mul_temp(6) OR Filter_Coefficient_mul_temp(5) OR Filter_Coefficient_mul_temp(4) OR Filter_Coefficient_mul_temp(3) OR Filter_Coefficient_mul_temp(2) OR Filter_Coefficient_mul_temp(1) OR Filter_Coefficient_mul_temp(0)))));

  Sum_add_temp <= Parallel_P_Gain_out1 + Integrator_x_reg;
  Sum_out1 <= Sum_add_temp + N_Gain_out1;

  y <= std_logic_vector(Sum_out1);

END rtl;

