-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\MATLAB_TO_VHDL3_SIMULINK\Subsystem1.vhd
-- Created: 2026-05-16 15:29:26
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.01
-- Target subsystem base rate: 0.01
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.01
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.01
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem1
-- Source Path: MATLAB_TO_VHDL3_SIMULINK/Subsystem1
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(63 DOWNTO 0);  -- double
        In2                               :   IN    std_logic_vector(63 DOWNTO 0);  -- double
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
        );
END Subsystem1;


ARCHITECTURE rtl OF Subsystem1 IS

  -- Component Declarations
  COMPONENT nfp_sub_comp
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_in2                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_out                         :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : nfp_sub_comp
    USE ENTITY work.nfp_sub_comp(rtl);

  -- Signals
  SIGNAL Sum_out1                         : std_logic_vector(63 DOWNTO 0);  -- ufix64

BEGIN
  u_nfp_sub_comp : nfp_sub_comp
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              nfp_in1 => In1,  -- double
              nfp_in2 => In2,  -- double
              nfp_out => Sum_out1  -- double
              );

  ce_out <= clk_enable;

  Out1 <= Sum_out1;

END rtl;

