-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\MATLAB_TO_VHDL3_SIMULINK\Subsystem1_pkg.vhd
-- Created: 2026-05-16 15:29:26
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Subsystem1_pkg IS
  TYPE vector_of_unsigned11 IS ARRAY (NATURAL RANGE <>) OF unsigned(10 DOWNTO 0);
  TYPE vector_of_signed57 IS ARRAY (NATURAL RANGE <>) OF signed(56 DOWNTO 0);
  TYPE vector_of_unsigned56 IS ARRAY (NATURAL RANGE <>) OF unsigned(55 DOWNTO 0);
  TYPE vector_of_unsigned52 IS ARRAY (NATURAL RANGE <>) OF unsigned(51 DOWNTO 0);
END Subsystem1_pkg;

