# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: o:/your_desired_folder/Ali/zz/SPI_ADC_GUI/SPI_ADC_GUI.srcs/sources_1/bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0.xci
# IP: The module: 'design_2_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/your_desired_folder/Ali/zz/SPI_ADC_GUI/SPI_ADC_GUI.srcs/sources_1/bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: o:/your_desired_folder/Ali/zz/SPI_ADC_GUI/SPI_ADC_GUI.srcs/sources_1/bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: o:/your_desired_folder/Ali/zz/SPI_ADC_GUI/SPI_ADC_GUI.srcs/sources_1/bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0.xci
# IP: The module: 'design_2_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/your_desired_folder/Ali/zz/SPI_ADC_GUI/SPI_ADC_GUI.srcs/sources_1/bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: o:/your_desired_folder/Ali/zz/SPI_ADC_GUI/SPI_ADC_GUI.srcs/sources_1/bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
