

function MicroBlaze_LED_GUI
    clc;

    % Global serial object
    s = [];

    % Main window
    fig = figure( ...
        'Name', 'MicroBlaze LED UART Control', ...
        'NumberTitle', 'off', ...
        'Position', [300 200 600 420], ...
        'MenuBar', 'none', ...
        'Resize', 'off');

    % Title
    uicontrol(fig, ...
        'Style', 'text', ...
        'String', 'MicroBlaze LED Control Panel', ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'Position', [120 370 360 30]);

    % COM Port label
    uicontrol(fig, ...
        'Style', 'text', ...
        'String', 'COM Port:', ...
        'FontSize', 11, ...
        'Position', [40 320 80 25]);

    % COM Port input
    comEdit = uicontrol(fig, ...
        'Style', 'edit', ...
        'String', 'COM3', ...
        'FontSize', 11, ...
        'Position', [120 320 100 30]);

    % Baudrate label
    uicontrol(fig, ...
        'Style', 'text', ...
        'String', 'Baudrate:', ...
        'FontSize', 11, ...
        'Position', [250 320 80 25]);

    % Baudrate input
    baudEdit = uicontrol(fig, ...
        'Style', 'edit', ...
        'String', '9600', ...
        'FontSize', 11, ...
        'Position', [330 320 100 30]);

    % Connect button
    connectBtn = uicontrol(fig, ...
        'Style', 'pushbutton', ...
        'String', 'Connect', ...
        'FontSize', 11, ...
        'Position', [460 320 100 30], ...
        'Callback', @connectSerial);

    % LED value label
    uicontrol(fig, ...
        'Style', 'text', ...
        'String', 'LED Decimal Value:', ...
        'FontSize', 12, ...
        'Position', [40 260 150 25]);

    ledValueText = uicontrol(fig, ...
        'Style', 'text', ...
        'String', '0', ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', 'white', ...
        'Position', [200 255 100 35]);

    % PWM label
    uicontrol(fig, ...
        'Style', 'text', ...
        'String', 'PWM Percent:', ...
        'FontSize', 12, ...
        'Position', [40 210 120 25]);

    pwmSlider = uicontrol(fig, ...
        'Style', 'slider', ...
        'Min', 0, ...
        'Max', 100, ...
        'Value', 50, ...
        'Position', [170 215 250 20], ...
        'Callback', @pwmChanged);

    pwmText = uicontrol(fig, ...
        'Style', 'text', ...
        'String', '50%', ...
        'FontSize', 12, ...
        'BackgroundColor', 'white', ...
        'Position', [440 205 70 35]);

    sendPwmBtn = uicontrol(fig, ...
        'Style', 'pushbutton', ...
        'String', 'Send PWM', ...
        'FontSize', 11, ...
        'Position', [250 170 100 30], ...
        'Callback', @sendPWM);

    % LED indicators
    ledLabels = gobjects(1, 8);
    ledBoxes = gobjects(1, 8);

    startX = 50;
    yLabel = 110;
    yBox = 70;

    for i = 1:8
        ledLabels(i) = uicontrol(fig, ...
            'Style', 'text', ...
            'String', sprintf('LED%d', i-1), ...
            'FontSize', 10, ...
            'Position', [startX + (i-1)*65, yLabel, 50, 20]);

        ledBoxes(i) = uicontrol(fig, ...
            'Style', 'text', ...
            'String', 'OFF', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [0.8 0.8 0.8], ...
            'Position', [startX + (i-1)*65, yBox, 50, 30]);
    end

    % Status text
    statusText = uicontrol(fig, ...
        'Style', 'text', ...
        'String', 'Status: Not Connected', ...
        'FontSize', 11, ...
        'HorizontalAlignment', 'left', ...
        'Position', [40 25 500 25]);

    % Timer for reading serial
    t = timer( ...
        'ExecutionMode', 'fixedSpacing', ...
        'Period', 0.2, ...
        'TimerFcn', @readSerial);

    % Close function
    fig.CloseRequestFcn = @closeGUI;

    % ================= Callback Functions =================

    function connectSerial(~, ~)
        try
            comPort = get(comEdit, 'String');
            baudRate = str2double(get(baudEdit, 'String'));
            if isempty(comPort) || isnan(baudRate)
                set(statusText, 'String', 'Status: Invalid COM port or baudrate');
                return;
            end

            s = serialport(comPort, baudRate);
            configureTerminator(s, "LF");
            flush(s);

            set(statusText, 'String', ['Status: Connected to ', comPort]);
            set(connectBtn, 'Enable', 'off');

            start(t);

        catch ME
            set(statusText, 'String', ['Status: Connection Error - ', ME.message]);
        end
    end

    function readSerial(~, ~)
        try
            if isempty(s)
                return;
            end

            if s.NumBytesAvailable > 0
                data = readline(s);
                data = strtrim(data);

                ledVal = str2double(data);

                if ~isnan(ledVal)
                    ledVal = max(0, min(255, round(ledVal)));
                    updateLEDDisplay(ledVal);
                end
            end

        catch
            % Ignore read errors
        end
    end

    function updateLEDDisplay(value)
        set(ledValueText, 'String', num2str(value));

        for k = 1:8
            bitVal = bitget(value, k);

            if bitVal == 1
                set(ledBoxes(k), ...
                    'String', 'ON', ...
                    'BackgroundColor', [0 1 0]);
            else
                set(ledBoxes(k), ...
                    'String', 'OFF', ...
                    'BackgroundColor', [0.8 0.8 0.8]);
            end
        end
    end

    function pwmChanged(~, ~)
        pwmValue = round(get(pwmSlider, 'Value'));
        set(pwmText, 'String', [num2str(pwmValue), '%']);
    end

    function sendPWM(~, ~)
        try
            if isempty(s)
                set(statusText, 'String', 'Status: Not connected');
                return;
            end

            pwmValue = round(get(pwmSlider, 'Value'));

            % Send PWM value as text with newline
            writeline(s, num2str(pwmValue));

            set(statusText, 'String', ['Status: PWM sent = ', num2str(pwmValue), '%']);

        catch ME
            set(statusText, 'String', ['Status: Send Error - ', ME.message]);
        end
    end

    function closeGUI(~, ~)
        try
            stop(t);
            delete(t);
        catch
        end

        try
            if ~isempty(s)
                clear s;
            end
        catch
        end

        delete(fig);
    end
end